# Generated by Django 2.1.2 on 2020-05-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='birthday',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
