# Generated by Django 2.1.2 on 2020-05-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_commentview'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentview',
            name='status',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
